### ISSUE TITLE
EasyRPG Player consideration

### ISSUE THREAD

**Issue by ghost** [ZabuzaW/TalesOfFreewar#1]
Hi, I was checking the screenshot from the wiki and it shows the text with the cleartype font issue.
To improve text readability, you may consider distributing it with [EasyRPG Player](https://github.com/EasyRPG/Player), an alternative interpreter which may replace RPG_RT.exe, it is cross platform and same license as your project (GPLv3).

About the RTP requirement, you may add the following line to RPG_RT.ini to prevent the error message if your game already contains all RTP required files:

`FullPackageFlag=1`

Regards.

**Comment by Zabuzard** [comment]
Thanks for the info! 👍
